/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.net.URL;
import javax.swing.Icon;
import javax.swing.JPanel;
import javax.swing.ImageIcon;

/**
 *
 * @author Duke
 */
public class Modelos extends javax.swing.JInternalFrame {

    
    private JPanel jdPrincipal;
    public Modelos(JPanel jdp) {
        initComponents();
        jdPrincipal = jdp;
    }

   
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        textArea2 = new java.awt.TextArea();

        textArea1.setBackground(new java.awt.Color(51, 51, 255));
        textArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textArea1.setEditable(false);
        textArea1.setMaximumSize(new java.awt.Dimension(767, 767));
        textArea1.setRows(30);
        textArea1.setText("A ANAC criou regras para as operações civis de aeronaves não tripuladas, também conhecidas como drones.\n\nO Regulamento Brasileiro de Aviação Civil Especial nº 94/2017 (RBAC-E nº 94/2017) da ANAC é complementar às normas \nde operação de drones estabelecidas pelo Departamento de Controle do Espaço Aéreo (DECEA) e pela Agência Nacional de\n Telecomunicações (ANATEL).\n\nPelo regulamento da ANAC, aeromodelos são as aeronaves não tripuladas remotamente pilotadas usadas para recreação e lazer e\nas aeronaves remotamente pilotadas (RPA) são as aeronaves não tripuladas utilizadas para outros fins como experimentais,\ncomerciais ou institucionais.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    // End of variables declaration//GEN-END:variables

        private void setIcon(Icon icon) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

    private static class imagemIcon {

        public void imagemIcon() {
            
        
        }

        private imagemIcon(URL resource) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
    }
