/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.net.URL;
import javax.swing.Icon;
import javax.swing.JPanel;
import javax.swing.ImageIcon;

/**
 *
 * @author Duke
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jdPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        ItemProduto = new javax.swing.JMenuItem();
        imCliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ItemSemi = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdPrincipal.setBackground(new java.awt.Color(16, 59, 45));
        jdPrincipal.setBorder(new javax.swing.border.MatteBorder(null));
        jdPrincipal.setForeground(new java.awt.Color(19, 78, 103));
        jdPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdPrincipal.setMaximumSize(new java.awt.Dimension(800, 900));

        jLabel1.setBackground(new java.awt.Color(24, 24, 24));
        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Drone Raiz");

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal);
        jdPrincipal.setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 255));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(167, 371));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(6, 6));

        jMenu3.setBackground(new java.awt.Color(0, 0, 255));
        jMenu3.setText("Cadastro");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ItemProduto.setBackground(new java.awt.Color(0, 0, 204));
        ItemProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemProduto.setForeground(new java.awt.Color(153, 153, 153));
        ItemProduto.setText("Produto");
        ItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(ItemProduto);

        imCliente.setBackground(new java.awt.Color(0, 0, 204));
        imCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imCliente.setForeground(new java.awt.Color(153, 153, 153));
        imCliente.setText("Cliente");
        imCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClienteActionPerformed(evt);
            }
        });
        jMenu3.add(imCliente);

        jMenuBar1.add(jMenu3);

        jMenu5.setBackground(new java.awt.Color(0, 0, 204));
        jMenu5.setText("Modelos");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ItemSemi.setBackground(new java.awt.Color(0, 0, 204));
        ItemSemi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemSemi.setForeground(new java.awt.Color(153, 153, 153));
        ItemSemi.setText("Semi-Profissonal");
        ItemSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSemiActionPerformed(evt);
            }
        });
        jMenu5.add(ItemSemi);

        jMenuItem4.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(153, 153, 153));
        jMenuItem4.setText("Profissonal");
        jMenu5.add(jMenuItem4);

        jMenuItem6.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(153, 153, 153));
        jMenuItem6.setText("Consumo");
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu2.setBackground(new java.awt.Color(0, 0, 255));
        jMenu2.setText("Sobre");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem2.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(153, 153, 153));
        jMenuItem2.setText("Informaçoes ao usuario");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(0, 0, 204));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(153, 153, 153));
        jMenuItem3.setText("Versao do Programa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jdPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void imClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClienteActionPerformed
        
        // TODO add your handling code here:
        ConsultarCliente consultaCliente = new ConsultarCliente( jdPrincipal);
        this.jdPrincipal.add(consultaCliente);
        consultaCliente.setVisible(true);
        
    }//GEN-LAST:event_imClienteActionPerformed

    private void ItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemProdutoActionPerformed
      ConsultarProduto consultaProduto = new ConsultarProduto( jdPrincipal);
        this.jdPrincipal.add(consultaProduto);
        consultaProduto.setVisible(true);
    }//GEN-LAST:event_ItemProdutoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ItemSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSemiActionPerformed
         Modelos  mod = new Modelos( jdPrincipal);
        this.jdPrincipal.add(mod);
        mod.setVisible(true);      
    }//GEN-LAST:event_ItemSemiActionPerformed

    

        
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
        /* Create and display the form */static {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
        
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemProduto;
    private javax.swing.JMenuItem ItemSemi;
    private javax.swing.JMenuItem imCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jdPrincipal;
    // End of variables declaration//GEN-END:variables

    

}
            
        
    
    
